server:
  port: 8083

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5432/dbs_customer_db
    username: dbs_user
    password: dbs_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: account-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.dbs.account.domain.event.CustomerCreatedEvent
        spring.json.trusted.packages: "com.dbs.*"

dbs:
  kafka:
    topics:
      customer-created: dbs.customer.created.v1